# Auto Firmware Dumper Workflow - Advanced Version
# Developed by: jisan ff <ffjisan804@gmail.com>
# New account by: frnwot <frnbuid2005@gmail.com>
#
# Developer Info Inputs added:
# - USER_NAME: Your GitHub username (e.g. "frnwot)
# - USER_EMAIL: Your GitHub email (e.g. "frnbuid2005@gmail.com")
# - DEVELOPER_URL: Your developer profile or Twitter (optional, e.g. "https://github.com/frnwot")
#
# Example usage via GitHub Actions workflow_dispatch UI or API:
#
# workflow_dispatch:
#   inputs:
#     USER_NAME: 'frnwot'
#     USER_EMAIL: 'frnbuid2005@gmail.com'
#     DEVELOPER_URL: 'https://github.com/frnwot'
#     FIRMWARE_URL: 'https://example.com/stockrom.zip'
#     GENERATE_VENDOR: true
#     UPLOAD_LINEAGE_DT: false
#     UPLOAD_TWRP_DT: true
#     USE_GENERIC_DUMPER_REPO: true

name: Auto Firmware Dumper

on:
  workflow_dispatch:
    inputs:
      USER_NAME:
        description: 'GitHub Username'
        required: true
      USER_EMAIL:
        description: 'GitHub Email'
        required: true
      DEVELOPER_URL:
        description: 'Developer Profile URL (optional)'
        required: false
      FIRMWARE_URL:
        description: 'Stock ROM Link (zip or payload.bin supported)'
        required: true
      GENERATE_VENDOR:
        description: 'Generate Vendor Tree'
        required: true
        default: false
        type: boolean
      UPLOAD_LINEAGE_DT:
        description: 'Upload LineageOS Device Tree'
        required: true
        default: false
        type: boolean
      UPLOAD_TWRP_DT:
        description: 'Upload TWRP Device Tree'
        required: true
        default: false
        type: boolean
      USE_GENERIC_DUMPER_REPO:
        description: 'Update Generic Dumper Repo If Exists'
        required: true
        default: false
        type: boolean

jobs:
  dumper:
    name: Firmware Dumper Execution
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      GH_TOKEN: ${{ secrets.GTOKEN }}
      UN: ${{ github.event.inputs.USER_NAME }}
      UEM: ${{ github.event.inputs.USER_EMAIL }}
      DEV_URL: ${{ github.event.inputs.DEVELOPER_URL }}
      FUR: ${{ github.event.inputs.FIRMWARE_URL }}
      GVT: ${{ github.event.inputs.GENERATE_VENDOR }}
      LOT: ${{ github.event.inputs.UPLOAD_LINEAGE_DT }}
      TWT: ${{ github.event.inputs.UPLOAD_TWRP_DT }}
      USE_GEN_REPO: ${{ github.event.inputs.USE_GENERIC_DUMPER_REPO }}
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update packages and install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y git curl aria2 cpio tar gzip neofetch python3 python3-pip
        echo -e "\033[1;32m✔ Dependencies installed\033[0m"

    - name: Install GitHub CLI
      run: |
        if ! command -v gh > /dev/null 2>&1; then
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update -y
          sudo apt install -y gh
        fi
        echo -e "\033[1;34m✔ GitHub CLI installed\033[0m"

    - name: Clone and setup DumprX with tools
      run: |
        mkdir -p ~/Auto-Dumper
        cd ~/Auto-Dumper
        rm -rf DumprX
        git clone https://github.com/frnwot/DumprX
        cd DumprX
        chmod +x *.sh
        bash setup.sh
        pip3 install --quiet --upgrade aospdtgen twrpdtgen
        echo -e "\033[1;36m✔ DumprX cloned and tools installed\033[0m"

    - name: Create firmware dump
      run: |
        cd ~/Auto-Dumper/DumprX
        bash dumper.sh "$FUR"
        chmod -R 777 out
        echo -e "\033[1;33m✔ Firmware dump complete\033[0m"

    - name: Configure Git and authenticate GitHub CLI
      run: |
        git config --global user.name "$UN"
        git config --global user.email "$UEM"
        echo "$GH_TOKEN" | gh auth login --with-token
        echo -e "\033[1;35m✔ Authenticated with GitHub CLI\033[0m"

    - name: Extract device info from dump
      run: |
        cd ~/Auto-Dumper/DumprX/out

        if [ ! -d system ]; then
          echo -e "\033[0;31mERROR: Dump failed, 'system' folder missing.\033[0m"
          exit 1
        fi

        cd system || cd vendor || exit 1

        codename=$(grep -m1 -E "ro.product.vendor.device|ro.vendor.product.device|ro.product.device" build.prop | cut -d= -f2 | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')
        brand=$(grep -m1 -E "ro.product.vendor.brand|ro.vendor.product.brand|ro.product.brand" build.prop | cut -d= -f2 | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')
        version=$(grep -m1 "ro.build.version.release_or_codename=" build.prop | cut -d= -f2)
        fingerprint=$(grep -m1 "ro.system.build.fingerprint=" build.prop | cut -d= -f2)

        if [ -z "$codename" ] || [ -z "$brand" ]; then
          echo -e "\033[0;31mERROR: Could not determine codename or brand.\033[0m"
          exit 1
        fi

        echo "$codename" > ~/Auto-Dumper/codename.txt
        echo "$brand" > ~/Auto-Dumper/brand.txt
        echo "$version" > ~/Auto-Dumper/version.txt
        echo "$fingerprint" > ~/Auto-Dumper/fingerprint.txt

        echo -e "\033[1;32m✔ Device info extracted: $brand $codename ($version)\033[0m"

    - name: Prepare project structure
      run: |
        cd ~/Auto-Dumper
        mkdir -p vnd_project/android/device/$(cat brand.txt)/$(cat codename.txt)
        mkdir -p vnd_project/dump

        if [ -d DumprX/out/lineage-device-tree ]; then
          mv DumprX/out/lineage-device-tree/* vnd_project/android/device/$(cat brand.txt)/$(cat codename.txt)
          rm -rf DumprX/out/lineage-device-tree
        else
          echo "Lineage device tree not found, skipping move."
        fi

        mv DumprX/out/* vnd_project/dump || echo "No dump files to move."
        echo -e "\033[1;36m✔ Project structure prepared\033[0m"

    - name: Generate vendor tree (if requested)
      if: env.GVT == 'true'
      run: |
        cd ~/Auto-Dumper/vnd_project
        brand=$(cat ../brand.txt)
        codename=$(cat ../codename.txt)

        if [ ! -d android/device/$brand/$codename ]; then
          echo -e "\033[0;31mERROR: LineageOS device tree not found at android/device/$brand/$codename\033[0m"
          exit 1
        fi

        git clone --depth=1 https://github.com/LineageOS/android_tools_extract-utils -b lineage-22.2 android/tools/extract-utils
        git clone --depth=1 https://github.com/LineageOS/android_prebuilts_extract-tools -b lineage-22.2 android/prebuilts/extract-tools

        chmod +x android/device/$brand/$codename/setup-makefiles.sh android/device/$brand/$codename/extract-files.sh
        bash android/device/$brand/$codename/extract-files.sh dump/

        echo -e "\033[1;34m✔ Vendor tree extraction complete\033[0m"

    - name: Upload vendor tree (if requested)
      if: env.GVT == 'true'
      run: |
        cd ~/Auto-Dumper/vnd_project/android/vendor/$(cat ../../brand.txt)/$(cat ../../codename.txt)
        git init
        git checkout -b vendor-"$(cat ../../../codename.txt)"-"$(date +%Y%m%d)"
        git add .
        git commit -s -m "$(cat ../../../codename.txt) : initial vendor tree"
        gh repo create android_vendor_"$(cat ../../../brand.txt)"_"$(cat ../../../codename.txt)" --public \
          --description="Vendor tree for $(cat ../../../codename.txt)" \
          --source=. --remote=origin --push --confirm
        echo -e "\033[1;32m✔ Vendor tree upload successful\033[0m"

    - name: Upload LineageOS device tree (if requested)
      if: env.LOT == 'true'
      run: |
        cd ~/Auto-Dumper/lineage-device-tree
        git init
        git checkout -b lineage-"$(cat ../codename.txt)"-"$(date +%Y%m%d)"
        git add .
        git commit -s -m "$(cat ../codename.txt) : LineageOS compatible device tree"
        gh repo create lineage_device_"$(cat ../brand.txt)"_"$(cat ../codename.txt)" --public \
          --description="LineageOS compatible device tree for $(cat ../codename.txt)" \
          --source=. --remote=origin --push --confirm
        echo -e "\033[1;34m✔ LineageOS device tree upload successful\033[0m"

    - name: Upload TWRP device tree (if requested)
      if: env.TWT == 'true'
      run: |
        cd ~/Auto-Dumper/twrp-device-tree/$(cat ../brand.txt)/$(cat ../codename.txt)
        if [ ! -f BoardConfig.mk ]; then
          cd */*
        fi
        git init
        git checkout -b twrp-"$(cat ../../version.txt)"-"$(date +%Y%m%d)"
        git add .
        git commit -s -m "$(cat ../../codename.txt) : TWRP compatible device tree"
        gh repo create twrp_device_"$(cat ../../brand.txt)"_"$(cat ../../codename.txt)" --public \
          --description="TWRP compatible device tree for $(cat ../../codename.txt)" \
          --source=. --remote=origin --push --confirm
        echo -e "\033[1;35m✔ TWRP device tree upload successful\033[0m"

    - name: Upload preview images as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Preview images
        path: |
          ~/Auto-Dumper/boot.img
          ~/Auto-Dumper/recovery.img
          ~/Auto-Dumper/vendor_boot.img
          ~/Auto-Dumper/init_boot.img
          ~/Auto-Dumper/dtbo.img
          ~/Auto-Dumper/dtb.img
        if-no-files-found: ignore

    - name: Generic dumper repo rename and push (optional)
      if: env.USE_GEN_REPO == 'true'
      run: |
        codename=$(cat ~/Auto-Dumper/codename.txt)
        brand=$(cat ~/Auto-Dumper/brand.txt)
        dat=$(date +%Y%m%d)
        repo_name="dump_${brand}_${codename}"

        echo "Searching for existing dumper repos owned by $UN ..."
        repos=$(gh repo list "$UN" --limit 100 --json name --jq '.[] | select(.name | startswith("dump_")) | .name')

        if echo "$repos" | grep -q "$repo_name"; then
          echo "Repo $repo_name found. Cloning and updating..."
          rm -rf ~/repo_update
          gh repo clone "$UN/$repo_name" ~/repo_update
          cd ~/repo_update
          git checkout main || git checkout master || git checkout -b main
          cp -r ~/Auto-Dumper/DumprX/out/* .
          git add .
          git commit -s -m "Update dump for $brand $codename on $dat" || echo "No changes to commit"
          git push origin HEAD
          echo -e "\033[1;32m✔ Repo updated successfully\033[0m"
        else
          echo "Repo $repo_name not found. Creating new repo and pushing..."
          mkdir -p ~/repo_update
          cp -r ~/Auto-Dumper/DumprX/out/* ~/repo_update
          cd ~/repo_update
          git init
          git checkout -b main
          git config user.name "$UN"
          git config user.email "$UEM"
          git add .
          git commit -s -m "Initial dump for $brand $codename on $dat"
          gh repo create "$repo_name" --public --description="Dump for $brand $codename created by $UN" --source=. --remote=origin --push --confirm
          echo -e "\033[1;32m✔ Repo created and pushed successfully\033[0m"
        fi
